# Generated by Django 5.0 on 2025-04-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenoms', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('stade', models.EmailField(max_length=254, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
