# Generated by Django 5.0 on 2025-04-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renale', '0002_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='stade',
            field=models.CharField(max_length=20),
        ),
    ]
