# Generated by Django 5.0 on 2025-04-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renale', '0003_alter_patient_stade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('tp', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=255)),
            ],
        ),
    ]
