# Generated by Django 5.0 on 2025-04-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renale', '0005_alter_patient_stade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='stade',
            field=models.IntegerField(),
        ),
    ]
