# Generated by Django 5.0 on 2025-04-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renale', '0006_alter_patient_stade'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='donnees_labo',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='stade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
